"""empty message

Revision ID: 0facfe743383
Revises: 9da76a62d8d7
Create Date: 2017-12-18 20:25:54.942621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0facfe743383'
down_revision = '9da76a62d8d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variety_detail',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.SmallInteger(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['variety_id'], ['varietys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variety_detail')
    # ### end Alembic commands ###
