"""empty message

Revision ID: 25da9dd4b7a1
Revises: 8189dd45ab40
Create Date: 2017-12-13 09:58:41.001353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25da9dd4b7a1'
down_revision = '8189dd45ab40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theatrical_films', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatrical_films', sa.Column('country', mysql.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
