"""empty message

Revision ID: 3c9c7bc748f0
Revises: 91845c2c7b85
Create Date: 2017-12-13 19:03:51.593874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9c7bc748f0'
down_revision = '91845c2c7b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_shows',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('profile', sa.String(length=128), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('premiere', sa.Date(), nullable=False),
    sa.Column('default_image', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('default_url', sa.String(length=128), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tv_shows_detail',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_shows_detail')
    op.drop_table('tv_shows')
    # ### end Alembic commands ###
