"""empty message

Revision ID: 8189dd45ab40
Revises: 564a8d888e83
Create Date: 2017-12-12 19:39:54.944290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8189dd45ab40'
down_revision = '564a8d888e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theatrical_films', sa.Column('url', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theatrical_films', 'url')
    # ### end Alembic commands ###
