"""empty message

Revision ID: 91845c2c7b85
Revises: 
Create Date: 2017-12-13 15:17:36.664548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91845c2c7b85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatrical_films',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('profile', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('premiere', sa.Date(), nullable=False),
    sa.Column('default_image', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('is_activate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('theatrical_films_comment',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=128), nullable=False),
    sa.Column('theatrical_film_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theatrical_film_id'], ['theatrical_films.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theatrical_films_comment')
    op.drop_table('users')
    op.drop_table('theatrical_films')
    # ### end Alembic commands ###
