"""empty message

Revision ID: 9da76a62d8d7
Revises: f1ca53e80dfe
Create Date: 2017-12-18 20:13:08.831044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da76a62d8d7'
down_revision = 'f1ca53e80dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('varietys',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('profile', sa.String(length=128), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('premiere', sa.Date(), nullable=False),
    sa.Column('default_image', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('varietys')
    # ### end Alembic commands ###
