"""empty message

Revision ID: bdef11f54199
Revises: 4cdf85aab0f8
Create Date: 2017-12-11 14:31:11.620021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdef11f54199'
down_revision = '4cdf85aab0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_activate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_activate')
    # ### end Alembic commands ###
