"""empty message

Revision ID: c0f690f00294
Revises: 8d72ec4f38b9
Create Date: 2017-12-11 16:30:17.130854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f690f00294'
down_revision = '8d72ec4f38b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
