"""empty message

Revision ID: d3f01d454732
Revises: f4989a08901a
Create Date: 2017-12-12 17:37:37.919314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f01d454732'
down_revision = 'f4989a08901a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teleplays',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('profile', sa.String(length=128), nullable=False),
    sa.Column('premiere', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=False),
    sa.Column('default_image', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teleplays')
    # ### end Alembic commands ###
