"""empty message

Revision ID: efa3bb5850fd
Revises: 8685be189374
Create Date: 2017-12-14 18:32:40.021120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efa3bb5850fd'
down_revision = '8685be189374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tv_shows', 'default_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tv_shows', sa.Column('default_url', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
