"""empty message

Revision ID: f1ca53e80dfe
Revises: efa3bb5850fd
Create Date: 2017-12-18 17:57:30.109664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ca53e80dfe'
down_revision = 'efa3bb5850fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_shows_comment',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=128), nullable=False),
    sa.Column('tv_show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tv_show_id'], ['tv_shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_shows_comment')
    # ### end Alembic commands ###
